### ISSUE TITLE
请问可以有个scala 教程么？

### ISSUE THREAD

**Issue by longde123** [AliCloudEngine/ace-java-demo#6]
rt

**Comment by oldratlee** [comment]
这个`Demo`用的是`Java`语言，实际上对于其它有`JVM`语言（如`Scala`、`Groovy`、`Clojure`），只要是个标准`WAR`的应用都是可以的。

@longde123 关于其它`JVM`语言（如`Scala`、`Groovy`、`Clojure`）如何写 `WAR`应用，你自己了解对应语言的资料吧，这些语言这边也用的不多。 :smile:

**Comment by longde123** [comment]
说的也是~~

@oldratlee小众语的开发人员才是最懒的程序员~~~不是么？哎哎~是我太懒了看demo上手快
